###(CREATE)
POST http://localhost:3000/user
Content-Type: application/json

{
    "username": "demo6",
    "password": "demo6"
}

###(READ)
GET http://localhost:3000/user

###(UPDATE)
# เปลี่ยน ":id" เป็น ID ของ user จริง เช่น /user/1
PUT http://localhost:3000/user/1
Content-Type: application/json

{
    "username": "ket",
    "password": "newPassword"
}

### (DELETE) - ลบผู้ใช้
# เปลี่ยน ":id" เป็น ID จริงของผู้ใช้ เช่น /user/4
DELETE http://localhost:3000/user/4
